export type SpeakingLevel = 'B1';

export interface SpeakingTopic {
  id: string;
  level: SpeakingLevel;
  teil: 2;
  title: string;
  positionA: string;
  positionB: string;
  followUpQuestions: string[];
}

export const SPEAKING_TOPICS: SpeakingTopic[] = [
  {
    id: 'b1-t2-001',
    level: 'B1',
    teil: 2,
    title: 'Reisen mit einer Gruppe',
    positionA: 'Gruppenreisen sind praktisch, weil alles organisiert ist.',
    positionB: 'Allein zu reisen gibt mehr Freiheit und Ruhe.',
    followUpQuestions: [
      'Wie reisen Sie am liebsten?',
      'Welche Erfahrungen haben Sie mit Gruppenreisen?',
      'Was ist bei einer Reise besonders wichtig?',
    ],
  },
  {
    id: 'b1-t2-002',
    level: 'B1',
    teil: 2,
    title: 'Urlaub im eigenen Land',
    positionA: 'Urlaub im eigenen Land ist günstig und unkompliziert.',
    positionB: 'Im Urlaub möchte ich neue Länder und Kulturen kennenlernen.',
    followUpQuestions: [
      'Wo verbringen Sie normalerweise Ihren Urlaub?',
      'Welche Vorteile hat Urlaub in der Nähe?',
      'Welches Reiseziel möchten Sie besuchen?',
    ],
  },
  {
    id: 'b1-t2-003',
    level: 'B1',
    teil: 2,
    title: 'Auto oder öffentliche Verkehrsmittel',
    positionA: 'Mit dem Auto ist man unabhängig und flexibel.',
    positionB: 'Bus und Bahn sind besser für die Umwelt und oft entspannter.',
    followUpQuestions: [
      'Welche Verkehrsmittel benutzen Sie täglich?',
      'Wann ist ein Auto sinnvoll?',
      'Wie könnte der öffentliche Verkehr besser werden?',
    ],
  },
  {
    id: 'b1-t2-004',
    level: 'B1',
    teil: 2,
    title: 'Fahrrad in der Stadt',
    positionA: 'Das Fahrrad ist das beste Verkehrsmittel für kurze Wege.',
    positionB: 'Radfahren in der Stadt ist zu gefährlich und unpraktisch.',
    followUpQuestions: [
      'Fahren Sie oft Fahrrad?',
      'Was brauchen sichere Fahrradwege?',
      'Für welche Wege eignet sich das Fahrrad nicht?',
    ],
  },
  {
    id: 'b1-t2-005',
    level: 'B1',
    teil: 2,
    title: 'Arbeiten im Homeoffice',
    positionA: 'Im Homeoffice kann man ruhig und flexibel arbeiten.',
    positionB: 'Im Büro ist der Kontakt mit Kolleginnen und Kollegen besser.',
    followUpQuestions: [
      'Wo arbeiten Sie lieber?',
      'Welche Probleme kann Homeoffice verursachen?',
      'Wie sieht ein guter Arbeitsplatz aus?',
    ],
  },
  {
    id: 'b1-t2-006',
    level: 'B1',
    teil: 2,
    title: 'Vier-Tage-Woche',
    positionA: 'Vier Arbeitstage bringen mehr Freizeit und Motivation.',
    positionB: 'In vier Tagen ist die gleiche Arbeit kaum zu schaffen.',
    followUpQuestions: [
      'Wie viele Tage möchten Sie arbeiten?',
      'Was macht Arbeitszeiten angenehm?',
      'Welche Berufe eignen sich für dieses Modell?',
    ],
  },
  {
    id: 'b1-t2-007',
    level: 'B1',
    teil: 2,
    title: 'Beruf oder gutes Gehalt',
    positionA: 'Eine interessante Arbeit ist wichtiger als ein hohes Gehalt.',
    positionB: 'Ein gutes Gehalt gibt Sicherheit und ist deshalb wichtiger.',
    followUpQuestions: [
      'Was ist Ihnen bei der Arbeit wichtig?',
      'Was macht einen Beruf interessant?',
      'Würden Sie für mehr Geld länger arbeiten?',
    ],
  },
  {
    id: 'b1-t2-008',
    level: 'B1',
    teil: 2,
    title: 'Weiterbildung neben dem Beruf',
    positionA: 'Weiterbildung verbessert die beruflichen Chancen.',
    positionB: 'Nach der Arbeit braucht man Erholung statt weiterer Kurse.',
    followUpQuestions: [
      'Haben Sie schon eine Weiterbildung gemacht?',
      'Wie kann man Lernen und Arbeit verbinden?',
      'Welche Fähigkeiten möchten Sie lernen?',
    ],
  },
  {
    id: 'b1-t2-009',
    level: 'B1',
    teil: 2,
    title: 'Online lernen',
    positionA: 'Onlinekurse sind flexibel und sparen Zeit.',
    positionB: 'Im Kursraum lernt man besser mit anderen Menschen.',
    followUpQuestions: [
      'Wie lernen Sie am liebsten?',
      'Was braucht ein guter Onlinekurs?',
      'Welche Rolle spielt die Lehrkraft?',
    ],
  },
  {
    id: 'b1-t2-010',
    level: 'B1',
    teil: 2,
    title: 'Hausaufgaben',
    positionA: 'Hausaufgaben helfen, den Unterrichtsstoff zu üben.',
    positionB:
      'Lernen sollte in der Schule stattfinden, damit Freizeit frei bleibt.',
    followUpQuestions: [
      'Welche Erfahrungen haben Sie mit Hausaufgaben?',
      'Wie viel Übung ist sinnvoll?',
      'Was hilft beim selbstständigen Lernen?',
    ],
  },
  {
    id: 'b1-t2-011',
    level: 'B1',
    teil: 2,
    title: 'Noten in der Schule',
    positionA: 'Noten zeigen klar, wie gut eine Leistung ist.',
    positionB: 'Persönliche Rückmeldungen helfen mehr als Zahlen.',
    followUpQuestions: [
      'Sind Noten gerecht?',
      'Wie kann man Leistung anders bewerten?',
      'Was motiviert Schülerinnen und Schüler?',
    ],
  },
  {
    id: 'b1-t2-012',
    level: 'B1',
    teil: 2,
    title: 'Fremdsprachen lernen',
    positionA: 'Man lernt eine Sprache am besten in einem Kurs.',
    positionB: 'Im Alltag und durch Gespräche lernt man schneller.',
    followUpQuestions: [
      'Wie lernen Sie Deutsch?',
      'Was ist beim Sprachenlernen schwierig?',
      'Welche Methoden helfen Ihnen?',
    ],
  },
  {
    id: 'b1-t2-013',
    level: 'B1',
    teil: 2,
    title: 'Smartphones im Unterricht',
    positionA: 'Smartphones können beim Lernen nützlich sein.',
    positionB: 'Smartphones lenken ab und gehören nicht in den Unterricht.',
    followUpQuestions: [
      'Wie können Smartphones beim Lernen helfen?',
      'Wann stören sie?',
      'Welche Regeln wären sinnvoll?',
    ],
  },
  {
    id: 'b1-t2-014',
    level: 'B1',
    teil: 2,
    title: 'Kinder und soziale Medien',
    positionA: 'Soziale Medien helfen Kindern, Kontakte zu pflegen.',
    positionB:
      'Kinder sollten soziale Medien erst ab einem höheren Alter nutzen.',
    followUpQuestions: [
      'Ab welchem Alter sind soziale Medien sinnvoll?',
      'Welche Gefahren gibt es?',
      'Wie können Eltern unterstützen?',
    ],
  },
  {
    id: 'b1-t2-015',
    level: 'B1',
    teil: 2,
    title: 'Nachrichten im Internet',
    positionA: 'Online findet man Nachrichten schnell und kostenlos.',
    positionB:
      'Zeitungen und öffentlich-rechtliche Angebote sind zuverlässiger.',
    followUpQuestions: [
      'Wo informieren Sie sich?',
      'Wie erkennt man falsche Nachrichten?',
      'Welche Themen interessieren Sie?',
    ],
  },
  {
    id: 'b1-t2-016',
    level: 'B1',
    teil: 2,
    title: 'Handyfreie Zeit',
    positionA: 'Jeden Tag sollte es feste Zeiten ohne Handy geben.',
    positionB: 'Jeder kann selbst entscheiden, wann er sein Handy benutzt.',
    followUpQuestions: [
      'Wie oft benutzen Sie Ihr Handy?',
      'Wann sollte das Handy ausgeschaltet sein?',
      'Was machen Sie gern ohne Bildschirm?',
    ],
  },
  {
    id: 'b1-t2-017',
    level: 'B1',
    teil: 2,
    title: 'Online einkaufen',
    positionA: 'Online einzukaufen ist bequem und bietet viel Auswahl.',
    positionB:
      'Im Geschäft bekommt man Beratung und kann Produkte direkt sehen.',
    followUpQuestions: [
      'Wo kaufen Sie lieber ein?',
      'Was bestellen Sie nicht online?',
      'Wie wichtig ist Beratung?',
    ],
  },
  {
    id: 'b1-t2-018',
    level: 'B1',
    teil: 2,
    title: 'Gebrauchte Sachen kaufen',
    positionA: 'Gebrauchte Produkte sind günstig und gut für die Umwelt.',
    positionB: 'Neue Produkte sind zuverlässiger und haben eine Garantie.',
    followUpQuestions: [
      'Was würden Sie gebraucht kaufen?',
      'Welche Erfahrungen haben Sie damit?',
      'Warum werfen Menschen brauchbare Dinge weg?',
    ],
  },
  {
    id: 'b1-t2-019',
    level: 'B1',
    teil: 2,
    title: 'Bargeld oder Karte',
    positionA: 'Mit Karte zu bezahlen ist schnell und praktisch.',
    positionB: 'Mit Bargeld behält man seine Ausgaben besser im Blick.',
    followUpQuestions: [
      'Wie bezahlen Sie meistens?',
      'Welche Zahlungsart ist sicherer?',
      'Sollte Bargeld erhalten bleiben?',
    ],
  },
  {
    id: 'b1-t2-020',
    level: 'B1',
    teil: 2,
    title: 'Werbung',
    positionA: 'Werbung informiert über neue und nützliche Produkte.',
    positionB: 'Werbung beeinflusst Menschen und schafft unnötige Wünsche.',
    followUpQuestions: [
      'Welche Werbung bemerken Sie?',
      'Hat Werbung Sie schon zu einem Kauf bewegt?',
      'Wo sollte Werbung begrenzt werden?',
    ],
  },
  {
    id: 'b1-t2-021',
    level: 'B1',
    teil: 2,
    title: 'Wohnung in der Stadt',
    positionA:
      'In der Stadt sind Arbeit, Kultur und Geschäfte schnell erreichbar.',
    positionB: 'Auf dem Land lebt man ruhiger und näher an der Natur.',
    followUpQuestions: [
      'Wo wohnen Sie lieber?',
      'Was ist Ihnen an einem Wohnort wichtig?',
      'Welche Nachteile hat das Stadtleben?',
    ],
  },
  {
    id: 'b1-t2-022',
    level: 'B1',
    teil: 2,
    title: 'Allein oder in einer Wohngemeinschaft',
    positionA:
      'In einer Wohngemeinschaft ist man nicht allein und teilt Kosten.',
    positionB: 'Eine eigene Wohnung bietet mehr Ruhe und Privatsphäre.',
    followUpQuestions: [
      'Welche Wohnform kennen Sie?',
      'Was muss man in einer WG regeln?',
      'Wie wichtig ist Privatsphäre?',
    ],
  },
  {
    id: 'b1-t2-023',
    level: 'B1',
    teil: 2,
    title: 'Haustiere in der Wohnung',
    positionA: 'Haustiere bereichern das Leben und geben Gesellschaft.',
    positionB: 'In kleinen Wohnungen sind Tiere oft nicht gut aufgehoben.',
    followUpQuestions: [
      'Haben Sie ein Haustier?',
      'Welche Verantwortung bedeutet ein Tier?',
      'Welche Tiere eignen sich für Wohnungen?',
    ],
  },
  {
    id: 'b1-t2-024',
    level: 'B1',
    teil: 2,
    title: 'Nachbarschaft',
    positionA: 'Gute Nachbarn sollten regelmäßig Kontakt miteinander haben.',
    positionB: 'Freundliche Distanz verhindert Probleme in der Nachbarschaft.',
    followUpQuestions: [
      'Kennen Sie Ihre Nachbarn?',
      'Wobei können Nachbarn helfen?',
      'Wie löst man Konflikte im Haus?',
    ],
  },
  {
    id: 'b1-t2-025',
    level: 'B1',
    teil: 2,
    title: 'Familienfeiern',
    positionA: 'Große Familienfeiern stärken den Zusammenhalt.',
    positionB: 'Kleine Treffen sind persönlicher und weniger anstrengend.',
    followUpQuestions: [
      'Wie feiern Sie mit Ihrer Familie?',
      'Was macht eine Feier angenehm?',
      'Wer sollte die Organisation übernehmen?',
    ],
  },
  {
    id: 'b1-t2-026',
    level: 'B1',
    teil: 2,
    title: 'Freundschaften im Internet',
    positionA:
      'Online kann man echte Freundschaften über große Entfernungen pflegen.',
    positionB: 'Für eine enge Freundschaft muss man sich persönlich treffen.',
    followUpQuestions: [
      'Wie halten Sie Kontakt zu Freunden?',
      'Kann eine Onlinefreundschaft genauso eng sein?',
      'Was ist in einer Freundschaft wichtig?',
    ],
  },
  {
    id: 'b1-t2-027',
    level: 'B1',
    teil: 2,
    title: 'Gemeinsame Mahlzeiten',
    positionA: 'Familien sollten mindestens einmal täglich gemeinsam essen.',
    positionB: 'Unterschiedliche Tagespläne machen feste Mahlzeiten unnötig.',
    followUpQuestions: [
      'Essen Sie oft mit anderen?',
      'Warum sind gemeinsame Mahlzeiten wichtig?',
      'Wer kocht bei Ihnen?',
    ],
  },
  {
    id: 'b1-t2-028',
    level: 'B1',
    teil: 2,
    title: 'Kinderbetreuung',
    positionA: 'Kleine Kinder profitieren früh von einer Kindertagesstätte.',
    positionB: 'Kleine Kinder sollten möglichst lange zu Hause betreut werden.',
    followUpQuestions: [
      'Welche Betreuung ist gut für Kinder?',
      'Welche Vorteile bietet eine Kita?',
      'Wie können Familien unterstützt werden?',
    ],
  },
  {
    id: 'b1-t2-029',
    level: 'B1',
    teil: 2,
    title: 'Sport im Verein',
    positionA:
      'Im Verein trainiert man regelmäßig und lernt neue Leute kennen.',
    positionB: 'Individuell Sport zu machen ist flexibler und günstiger.',
    followUpQuestions: [
      'Welchen Sport machen Sie?',
      'Was bietet ein Sportverein?',
      'Wie motivieren Sie sich zum Training?',
    ],
  },
  {
    id: 'b1-t2-030',
    level: 'B1',
    teil: 2,
    title: 'Fitnessstudio',
    positionA: 'Ein Fitnessstudio bietet Geräte und Training bei jedem Wetter.',
    positionB: 'Bewegung draußen ist angenehmer und kostet nichts.',
    followUpQuestions: [
      'Wo treiben Sie lieber Sport?',
      'Was motiviert zum regelmäßigen Training?',
      'Wie viel Bewegung braucht man?',
    ],
  },
  {
    id: 'b1-t2-031',
    level: 'B1',
    teil: 2,
    title: 'Gesunde Ernährung',
    positionA: 'Gesundes Essen muss täglich geplant und frisch gekocht werden.',
    positionB:
      'Auch mit wenig Zeit kann man sich ohne strenge Regeln ausgewogen ernähren.',
    followUpQuestions: [
      'Was bedeutet gesunde Ernährung für Sie?',
      'Wie oft kochen Sie?',
      'Was erschwert gesundes Essen?',
    ],
  },
  {
    id: 'b1-t2-032',
    level: 'B1',
    teil: 2,
    title: 'Vegetarisches Essen',
    positionA: 'Weniger Fleisch ist gut für Gesundheit, Tiere und Umwelt.',
    positionB:
      'Fleisch gehört für viele Menschen zu einer ausgewogenen Ernährung.',
    followUpQuestions: [
      'Wie oft essen Sie Fleisch?',
      'Welche vegetarischen Gerichte mögen Sie?',
      'Sollte es mehr fleischfreie Angebote geben?',
    ],
  },
  {
    id: 'b1-t2-033',
    level: 'B1',
    teil: 2,
    title: 'Fertiggerichte',
    positionA: 'Fertiggerichte sind eine praktische Lösung bei wenig Zeit.',
    positionB: 'Selbst gekochtes Essen schmeckt besser und ist gesünder.',
    followUpQuestions: [
      'Wann nutzen Sie Fertiggerichte?',
      'Was kochen Sie schnell?',
      'Wie wichtig sind Zutaten?',
    ],
  },
  {
    id: 'b1-t2-034',
    level: 'B1',
    teil: 2,
    title: 'Arztbesuch per Video',
    positionA: 'Eine Videosprechstunde spart Wege und Wartezeit.',
    positionB:
      'Eine gute Untersuchung ist nur persönlich in der Praxis möglich.',
    followUpQuestions: [
      'Würden Sie eine Videosprechstunde nutzen?',
      'Für welche Beschwerden eignet sie sich?',
      'Was ist beim Arztbesuch wichtig?',
    ],
  },
  {
    id: 'b1-t2-035',
    level: 'B1',
    teil: 2,
    title: 'Stress im Alltag',
    positionA: 'Ein genauer Tagesplan hilft gegen Stress.',
    positionB: 'Mehr freie Zeit ohne feste Pläne ist die beste Erholung.',
    followUpQuestions: [
      'Was verursacht bei Ihnen Stress?',
      'Wie erholen Sie sich?',
      'Welche Rolle spielt Zeitplanung?',
    ],
  },
  {
    id: 'b1-t2-036',
    level: 'B1',
    teil: 2,
    title: 'Früh aufstehen',
    positionA: 'Wer früh aufsteht, kann den Tag besser nutzen.',
    positionB: 'Menschen arbeiten zu unterschiedlichen Tageszeiten am besten.',
    followUpQuestions: [
      'Wann beginnt Ihr Tag?',
      'Wann sind Sie besonders produktiv?',
      'Wie wichtig ist genug Schlaf?',
    ],
  },
  {
    id: 'b1-t2-037',
    level: 'B1',
    teil: 2,
    title: 'Hobbys',
    positionA: 'Ein festes Hobby ist wichtig als Ausgleich zum Alltag.',
    positionB:
      'Man kann seine Freizeit spontan und ohne festes Hobby genießen.',
    followUpQuestions: [
      'Welche Hobbys haben Sie?',
      'Wie finden Menschen ein passendes Hobby?',
      'Wie viel Zeit sollte man dafür haben?',
    ],
  },
  {
    id: 'b1-t2-038',
    level: 'B1',
    teil: 2,
    title: 'Bücher oder Filme',
    positionA: 'Bücher lassen mehr Raum für Fantasie und Details.',
    positionB: 'Filme erzählen Geschichten lebendig und in kurzer Zeit.',
    followUpQuestions: [
      'Lesen Sie lieber oder sehen Sie Filme?',
      'Welches Buch oder welchen Film empfehlen Sie?',
      'Wo erleben Sie Geschichten am liebsten?',
    ],
  },
  {
    id: 'b1-t2-039',
    level: 'B1',
    teil: 2,
    title: 'Kino oder Streaming',
    positionA: 'Im Kino sind Bild, Ton und Atmosphäre besonders.',
    positionB: 'Streaming zu Hause ist bequemer und günstiger.',
    followUpQuestions: [
      'Wie sehen Sie Filme?',
      'Was gehört zu einem guten Filmabend?',
      'Hat das Kino eine Zukunft?',
    ],
  },
  {
    id: 'b1-t2-040',
    level: 'B1',
    teil: 2,
    title: 'Musikveranstaltungen',
    positionA: 'Livekonzerte bieten ein besonderes gemeinsames Erlebnis.',
    positionB: 'Musik zu Hause zu hören ist entspannter und viel günstiger.',
    followUpQuestions: [
      'Welche Musik hören Sie?',
      'Besuchen Sie Konzerte?',
      'Was macht Live-Musik besonders?',
    ],
  },
  {
    id: 'b1-t2-041',
    level: 'B1',
    teil: 2,
    title: 'Museen kostenlos',
    positionA:
      'Museen sollten kostenlos sein, damit alle Kultur erleben können.',
    positionB:
      'Eintrittspreise sind nötig, um gute Ausstellungen zu finanzieren.',
    followUpQuestions: [
      'Besuchen Sie Museen?',
      'Wer sollte Kultur bezahlen?',
      'Wie werden Museen interessanter?',
    ],
  },
  {
    id: 'b1-t2-042',
    level: 'B1',
    teil: 2,
    title: 'Feste in der Stadt',
    positionA: 'Stadtfeste bringen Menschen zusammen und beleben den Ort.',
    positionB: 'Große Feste verursachen Lärm, Müll und hohe Kosten.',
    followUpQuestions: [
      'Welche Feste kennen Sie?',
      'Was macht ein gutes Stadtfest aus?',
      'Wie kann man Störungen reduzieren?',
    ],
  },
  {
    id: 'b1-t2-043',
    level: 'B1',
    teil: 2,
    title: 'Ehrenamt',
    positionA: 'Jeder sollte einen Teil seiner Freizeit freiwillig helfen.',
    positionB: 'Hilfe ist wichtig, aber nicht jeder hat Zeit für ein Ehrenamt.',
    followUpQuestions: [
      'Haben Sie schon freiwillig geholfen?',
      'Welche Bereiche brauchen Unterstützung?',
      'Was motiviert Menschen zum Ehrenamt?',
    ],
  },
  {
    id: 'b1-t2-044',
    level: 'B1',
    teil: 2,
    title: 'Gemeinschaftsgarten',
    positionA:
      'Gemeinschaftsgärten verbessern das Viertel und verbinden Menschen.',
    positionB: 'Öffentliche Flächen sollten für Parks und Sport frei bleiben.',
    followUpQuestions: [
      'Gärtnern Sie gern?',
      'Was kann ein Gemeinschaftsgarten bieten?',
      'Wie teilt man die Arbeit gerecht?',
    ],
  },
  {
    id: 'b1-t2-045',
    level: 'B1',
    teil: 2,
    title: 'Müll vermeiden',
    positionA: 'Verbraucher müssen Produkte mit wenig Verpackung wählen.',
    positionB:
      'Hersteller und Politik tragen die Hauptverantwortung für weniger Müll.',
    followUpQuestions: [
      'Wie vermeiden Sie Müll?',
      'Welche Verpackungen sind unnötig?',
      'Wer kann am meisten verändern?',
    ],
  },
  {
    id: 'b1-t2-046',
    level: 'B1',
    teil: 2,
    title: 'Plastiktüten verbieten',
    positionA: 'Ein Verbot reduziert schnell unnötigen Plastikmüll.',
    positionB:
      'Information und freiwillige Änderungen sind besser als Verbote.',
    followUpQuestions: [
      'Benutzen Sie Stofftaschen?',
      'Wo ist Plastik schwer zu ersetzen?',
      'Welche Regeln helfen der Umwelt?',
    ],
  },
  {
    id: 'b1-t2-047',
    level: 'B1',
    teil: 2,
    title: 'Regionale Lebensmittel',
    positionA:
      'Regionale Produkte sind frischer und unterstützen lokale Betriebe.',
    positionB: 'Preis und Qualität sind wichtiger als die Herkunft.',
    followUpQuestions: [
      'Wo kaufen Sie Lebensmittel?',
      'Was bedeutet regional?',
      'Dürfen regionale Produkte mehr kosten?',
    ],
  },
  {
    id: 'b1-t2-048',
    level: 'B1',
    teil: 2,
    title: 'Kleidung und Mode',
    positionA: 'Mode ist eine wichtige Möglichkeit, Persönlichkeit zu zeigen.',
    positionB:
      'Kleidung sollte vor allem praktisch, langlebig und günstig sein.',
    followUpQuestions: [
      'Wie wichtig ist Mode für Sie?',
      'Wie oft kaufen Sie Kleidung?',
      'Was macht gute Kleidung aus?',
    ],
  },
  {
    id: 'b1-t2-049',
    level: 'B1',
    teil: 2,
    title: 'Reparieren statt wegwerfen',
    positionA: 'Kaputte Geräte sollten möglichst repariert werden.',
    positionB: 'Neue Geräte sind oft günstiger, sicherer und energiesparender.',
    followUpQuestions: [
      'Was haben Sie schon repariert?',
      'Warum sind Reparaturen manchmal teuer?',
      'Welche Geräte sollten länger halten?',
    ],
  },
  {
    id: 'b1-t2-050',
    level: 'B1',
    teil: 2,
    title: 'Urlaubsflüge',
    positionA: 'Flugreisen ermöglichen schnell den Besuch ferner Länder.',
    positionB: 'Für den Klimaschutz sollten Menschen seltener fliegen.',
    followUpQuestions: [
      'Wie oft fliegen Sie?',
      'Welche Alternativen gibt es?',
      'Sollten Flüge teurer sein?',
    ],
  },
  {
    id: 'b1-t2-051',
    level: 'B1',
    teil: 2,
    title: 'Deutsch am Arbeitsplatz',
    positionA:
      'Am Arbeitsplatz sollte möglichst nur Deutsch gesprochen werden.',
    positionB: 'Mehrere Sprachen können Teams und Kunden helfen.',
    followUpQuestions: [
      'Welche Sprachen nutzen Sie bei der Arbeit?',
      'Wann ist eine gemeinsame Sprache wichtig?',
      'Wie können Betriebe beim Deutschlernen helfen?',
    ],
  },
  {
    id: 'b1-t2-052',
    level: 'B1',
    teil: 2,
    title: 'Pünktlichkeit',
    positionA: 'Pünktlichkeit zeigt Respekt und ist immer wichtig.',
    positionB:
      'Bei privaten Treffen sollten kleine Verspätungen kein Problem sein.',
    followUpQuestions: [
      'Wie wichtig ist Pünktlichkeit für Sie?',
      'Wann ist eine Verspätung verständlich?',
      'Was tun Sie, wenn Sie zu spät kommen?',
    ],
  },
  {
    id: 'b1-t2-053',
    level: 'B1',
    teil: 2,
    title: 'Mittagspause gemeinsam verbringen',
    positionA: 'Gemeinsame Pausen verbessern das Verhältnis im Team.',
    positionB: 'In der Pause braucht man Ruhe und Zeit für sich.',
    followUpQuestions: [
      'Wie verbringen Sie Ihre Pause?',
      'Sollten Teams zusammen essen?',
      'Was gehört zu einer guten Pause?',
    ],
  },
  {
    id: 'b1-t2-054',
    level: 'B1',
    teil: 2,
    title: 'Arbeitskleidung',
    positionA: 'Einheitliche Kleidung wirkt professionell und praktisch.',
    positionB: 'Beschäftigte sollten ihre Kleidung selbst wählen dürfen.',
    followUpQuestions: [
      'Gibt es in Ihrem Beruf Arbeitskleidung?',
      'Wann ist sie notwendig?',
      'Wer sollte sie bezahlen?',
    ],
  },
  {
    id: 'b1-t2-055',
    level: 'B1',
    teil: 2,
    title: 'Bewerbungsgespräch online',
    positionA: 'Onlinegespräche sparen Bewerbenden und Firmen Zeit.',
    positionB: 'Persönlich bekommt man einen besseren Eindruck voneinander.',
    followUpQuestions: [
      'Hatten Sie schon ein Bewerbungsgespräch?',
      'Wie bereitet man sich online vor?',
      'Was ist für den ersten Eindruck wichtig?',
    ],
  },
  {
    id: 'b1-t2-056',
    level: 'B1',
    teil: 2,
    title: 'Geschenke',
    positionA: 'Persönliche Geschenke zeigen Aufmerksamkeit und Freude.',
    positionB: 'Gemeinsame Zeit ist wertvoller als gekaufte Dinge.',
    followUpQuestions: [
      'Was schenken Sie gern?',
      'Was war Ihr schönstes Geschenk?',
      'Sind Geldgeschenke unpersönlich?',
    ],
  },
  {
    id: 'b1-t2-057',
    level: 'B1',
    teil: 2,
    title: 'Geburtstag groß feiern',
    positionA: 'Ein Geburtstag ist ein guter Anlass für eine große Feier.',
    positionB: 'Ein ruhiger Tag mit wenigen vertrauten Menschen ist schöner.',
    followUpQuestions: [
      'Wie feiern Sie Ihren Geburtstag?',
      'Was kostet eine gute Feier?',
      'Welche Aufgaben gehören zur Organisation?',
    ],
  },
  {
    id: 'b1-t2-058',
    level: 'B1',
    teil: 2,
    title: 'Urlaubsfotos teilen',
    positionA: 'Fotos in sozialen Medien lassen Freunde an Reisen teilhaben.',
    positionB:
      'Private Reiseerlebnisse und Fotos gehören nicht öffentlich ins Internet.',
    followUpQuestions: [
      'Teilen Sie Urlaubsfotos?',
      'Welche Bilder sollten privat bleiben?',
      'Warum fotografieren Menschen auf Reisen?',
    ],
  },
  {
    id: 'b1-t2-059',
    level: 'B1',
    teil: 2,
    title: 'Wochenende planen',
    positionA: 'Mit einem Plan kann man das Wochenende besser nutzen.',
    positionB: 'Am Wochenende sollte man spontan entscheiden und sich erholen.',
    followUpQuestions: [
      'Planen Sie Ihr Wochenende?',
      'Was machen Sie bei schlechtem Wetter?',
      'Wie finden Sie Zeit für Erholung?',
    ],
  },
  {
    id: 'b1-t2-060',
    level: 'B1',
    teil: 2,
    title: 'Neue Menschen kennenlernen',
    positionA: 'Kurse und Vereine sind der beste Weg, neue Kontakte zu finden.',
    positionB: 'Freundschaften entstehen am besten spontan im Alltag.',
    followUpQuestions: [
      'Wo lernen Sie neue Menschen kennen?',
      'Was erleichtert ein erstes Gespräch?',
      'Wie bleibt man in Kontakt?',
    ],
  },
];
