-- ============================================================
-- SEED 006 — Sprachbausteine Teil 2, Modelltest 1
-- Source: Mit Erfolg zu telc Deutsch B1+ Beruf, Klett 2015, p. 15
-- Answers verified from Lösungen page 81
--
-- Correct answers: 31a  32m  33d  34c  35o  36n  37g  38e  39h  40l
-- Decoys (no gap):  b(ARBEIT)  f(BESONDEREN)  i(KARRIERE)
--                   j(LESEN)   k(NAHM)
--
-- Strategy: DB generates all UUIDs. Gaps reference words via
-- (SELECT id … WHERE letter = 'x') subquery — a wrong letter
-- produces NULL which violates the NOT NULL constraint immediately.
-- ============================================================

BEGIN;

-- ── 1. Exercise ──────────────────────────────────────────────

INSERT INTO sprachbausteine_teil2_exercises
  ("contentRevision", label, instruction, "durationMinutes", body)
VALUES (
  'modelltest-1-sprachbausteine-teil2-v1',
  '',
  'Lesen Sie den Text und schließen Sie die Lücken 31–40. Benutzen Sie die Wörter a–o. Jedes Wort passt nur einmal. Markieren Sie Ihre Lösungen für die Aufgaben 31–40 auf dem Antwortbogen.',
  18,
  E'Olga Fedorow\nSichelstr. 11 b\n40625 Düsseldorf\n\nStädtisches Klinikum Solingen gemeinnützige GmbH\nPersonalmanagement\nGotenstraße 1\n42653 Solingen\n\nDüsseldorf, 26. 07. 2015\n\nBewerbung\n\nSehr geehrte Damen und Herren,\n\nin der WELT habe ich Ihre -31- gefunden, die mich sofort interessierte.\nUm die ausgeschriebene -32- der stellvertretenden Pflegedienstleitung -33- ich mich.\n\nIn Russland habe ich meine schulische und berufliche -34- erhalten und drei Jahre praktische\nErfahrungen im Krankenhaus sammeln können. Nach unserer Übersiedlung nach Österreich\nhabe ich meine Sprachkenntnisse -35- und fand im Allgemeinen Krankenhaus der Stadt Wien\neine Anstellung als Stationsschwester. Nach einem Jahr -36- ich die Pflegedienstleitung in der\nGynäkologischen Abteilung.\n\nJetzt hat mein Mann in Düsseldorf eine attraktive Stelle als IT-Systemkoordinator angeboten\nbekommen, und so sind wir kurzentschlossen hierher umgezogen.\nIch möchte diese Veränderung als -37- nutzen, um neue Erfahrungen in leitender Position eines\ngroßen Klinikums zu sammeln.\n\nEinzelheiten meiner Ausbildung und meines -38- Werdegangs können Sie meinem\nLebenslauf und den beigefügten Zeugnissen/Bescheinigungen -39- . Über die Möglichkeit eines\n-40- Gespräches würde ich mich freuen.\n\nMit freundlichen Grüßen\nOlga Fedorow\nAnlagen'
);

-- ── 2. Words (15 items, UUIDs generated by DB) ───────────────

INSERT INTO sprachbausteine_teil2_words
  ("exerciseId", letter, content, "sortOrder")
SELECT
  e.id,
  w.letter,
  w.content,
  w.sort_order
FROM sprachbausteine_teil2_exercises e,
(VALUES
  ('a', 'ANZEIGE',      0),
  ('b', 'ARBEIT',       1),
  ('c', 'AUSBILDUNG',   2),
  ('d', 'BEWERBE',      3),
  ('e', 'BERUFLICHEN',  4),
  ('f', 'BESONDEREN',   5),
  ('g', 'CHANCE',       6),
  ('h', 'ENTNEHMEN',    7),
  ('i', 'KARRIERE',     8),
  ('j', 'LESEN',        9),
  ('k', 'NAHM',        10),
  ('l', 'PERSÖNLICHEN',11),
  ('m', 'STELLE',      12),
  ('n', 'ÜBERNAHM',    13),
  ('o', 'VERBESSERT',  14)
) AS w(letter, content, sort_order)
WHERE e."contentRevision" = 'modelltest-1-sprachbausteine-teil2-v1';

-- ── 3. Gaps (10 items, linked by letter subquery) ────────────
-- Each (SELECT id …) either returns the word UUID or NULL.
-- NULL violates correctWordId NOT NULL → immediate insert failure.

INSERT INTO sprachbausteine_teil2_gaps
  ("exerciseId", "gapKey", "gapNumber", "correctWordId", "sortOrder")
SELECT
  e.id,
  g.gap_key,
  g.gap_number::int,
  (SELECT w.id FROM sprachbausteine_teil2_words w
   WHERE w."exerciseId" = e.id AND w.letter = g.correct_letter),
  g.sort_order::int
FROM sprachbausteine_teil2_exercises e,
(VALUES
  ('31', 31, 'a', 0),
  ('32', 32, 'm', 1),
  ('33', 33, 'd', 2),
  ('34', 34, 'c', 3),
  ('35', 35, 'o', 4),
  ('36', 36, 'n', 5),
  ('37', 37, 'g', 6),
  ('38', 38, 'e', 7),
  ('39', 39, 'h', 8),
  ('40', 40, 'l', 9)
) AS g(gap_key, gap_number, correct_letter, sort_order)
WHERE e."contentRevision" = 'modelltest-1-sprachbausteine-teil2-v1';

COMMIT;
