export const AUTH_ERROR_MESSAGES: Record<string, string> = {
  ACTIVATION_CODE_NOT_FOUND: 'Activation code not found',
  ACTIVATION_CODE_INVALID: 'Activation code is invalid',
  ACTIVATION_CODE_EXPIRED: 'Activation code has expired',
  ACTIVATION_CODE_ALREADY_CLAIMED: 'Activation code already claimed',
  ACTIVATION_CODE_ALREADY_USED: 'Activation code already used',
  DEVICE_LIMIT_REACHED: 'Device limit reached',
  INVALID_ACCESS_TOKEN: 'Invalid access token',
  INVALID_REFRESH_TOKEN: 'Invalid refresh token',
  SESSION_NOT_FOUND: 'Session not found',
  SESSION_REVOKED: 'Session revoked',
  TOKEN_MISMATCH: 'Refresh token mismatch',
  MEMBERSHIP_EXPIRED: 'Membership expired',
  EMAIL_ALREADY_IN_USE: 'Email already in use',
  INVALID_EMAIL_FORMAT: 'Invalid email format',
  INVALID_NAME_FORMAT: 'Invalid name format',
  RATE_LIMIT_EXCEEDED: 'Too many activation attempts. Try again later.',
  INVALID_ACTIVATION_CODE: 'Activation code is invalid',
  STUDENT_NOT_FOUND: 'Student not found',
  MISSING_REQUIRED_FIELDS: 'Missing required fields',
  REGISTRATION_FAILED: 'Registration failed',
  DEVICE_SESSION_CREATION_FAILED: 'Device session creation failed',
  INVALID_SESSION: 'Invalid session',
  PROFILE_UPDATE_FAILED: 'Profile update failed',
  SESSION_UPDATE_FAILED: 'Session update failed',
  SESSION_REVOKE_FAILED: 'Session revoke failed',
  NO_PROFILE_FIELDS: 'No profile fields provided',
  NO_ACTIVE_SESSION: 'No active session found for device',
  VALIDATION_ERROR: 'Validation error',
};
