import { applyDecorators } from '@nestjs/common';
import { ApiPropertyOptional } from '@nestjs/swagger';
import { IsOptional, IsUUID } from 'class-validator';

/**
 * The id the app gives an attempt before sending it, so a retried submit is
 * stored once (D29). Optional: without it every submit is a new attempt.
 */
export function ClientAttemptId() {
  return applyDecorators(
    ApiPropertyOptional({
      format: 'uuid',
      description:
        'Generated by the app for this attempt. Sending the same attempt again with the same id stores it once and returns the first result.',
    }),
    IsOptional(),
    IsUUID(),
  );
}
